import { InspectorThemeDefinition } from 'react-inspector';

export const mono = 'Menlo, Monaco, "Lucida Console", "Liberation Mono", "DejaVu Sans Mono", "Bitstream Vera Sans Mono", "Courier New", monospace';

const theme: InspectorThemeDefinition = {
  BASE_FONT_FAMILY: mono,
  BASE_FONT_SIZE: '12px',
  BASE_LINE_HEIGHT: 1.2,

  BASE_BACKGROUND_COLOR: '#000',
  BASE_COLOR: '#7928CA',

  OBJECT_PREVIEW_ARRAY_MAX_PROPERTIES: 10,
  OBJECT_PREVIEW_OBJECT_MAX_PROPERTIES: 5,
  OBJECT_NAME_COLOR: '#fafafa',
  OBJECT_VALUE_NULL_COLOR: '#7928CA',
  OBJECT_VALUE_UNDEFINED_COLOR: '#7928CA',
  OBJECT_VALUE_REGEXP_COLOR: '#F81CE5',
  OBJECT_VALUE_STRING_COLOR: '#F81CE5',
  OBJECT_VALUE_SYMBOL_COLOR: '#F81CE5',
  OBJECT_VALUE_NUMBER_COLOR: '#79ffe1',
  OBJECT_VALUE_BOOLEAN_COLOR: '#79ffe1',
  OBJECT_VALUE_FUNCTION_PREFIX_COLOR: '#fff',

  HTML_TAG_COLOR: 'rgb(93, 176, 215)',
  HTML_TAGNAME_COLOR: 'rgb(93, 176, 215)',
  HTML_TAGNAME_TEXT_TRANSFORM: 'lowercase',
  HTML_ATTRIBUTE_NAME_COLOR: 'rgb(155, 187, 220)',
  HTML_ATTRIBUTE_VALUE_COLOR: 'rgb(242, 151, 102)',
  HTML_COMMENT_COLOR: 'rgb(137, 137, 137)',
  HTML_DOCTYPE_COLOR: 'rgb(192, 192, 192)',

  ARROW_COLOR: '#fff',
  ARROW_MARGIN_RIGHT: '4px',
  ARROW_FONT_SIZE: '12px',
  ARROW_ANIMATION_DURATION: '0',

  TREENODE_FONT_FAMILY: mono,
  TREENODE_FONT_SIZE: '12px',
  TREENODE_LINE_HEIGHT: 1,
  TREENODE_PADDING_LEFT: '16px',

  TABLE_BORDER_COLOR: 'rgb(85, 85, 85)',
  TABLE_TH_BACKGROUND_COLOR: 'rgb(44, 44, 44)',
  TABLE_TH_HOVER_COLOR: 'rgb(48, 48, 48)',
  TABLE_SORT_ICON_COLOR: 'black',
  TABLE_DATA_BACKGROUND_IMAGE:
    'linear-gradient(rgba(255, 255, 255, 0), rgba(255, 255, 255, 0) 50%, rgba(51, 139, 255, 0.0980392) 50%, rgba(51, 139, 255, 0.0980392))',
  TABLE_DATA_BACKGROUND_SIZE: '128px 32px',
};

export default theme;
